language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

jobs:
  include:
    - stage: compile
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew test
    - stage: analysis
      addons:
        sonarcloud:
          organization: "mrombout-github"
      script: ./gradlew sonarqube
    - stage: feature
      script: ./gradlew cucumber
    - stage: release

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
