language: java
jdk:
  - oraclejdk8
addons:
  srcclr: true
  sonarqube:
    token:
      secure: "err1BmNylfcJLnzc/67lY49DcFhQ0TWsHzTG7VbbbdodAIsTJBB3gHQOU8oIv8TQCRkKpvDjNcCuieF3QipEU6c0MBkIdTjfGzuPu8t1pOrIkNkFDqd1qBXYa+VWsdJDHdxR6rF8kcKl2OPMbS5LaN9rcRq8t3WoFoJdXDpJF/dN0CNA78pKQr9cX8gPkc0g9F/8SzKuoMZ+pMjBNbzMzOb0UlawjGgs4Px2bRbuBL/rThTZgaXhIl91oAlQwov24ann1vLFIqExc4GH7CxxBmZaiakMxpJQTOgryYs1tsNd4tmCmRG1qGr5orEMVU/vg7ZMAqcgvns2kVT9EzUxzzl8dPEg3JQg9V+3T3HKp15kkCPbAoCETqr+f+JCkO9DRvEpR010SU71RX6mH6/YjTJYoh0Cwrk+5nKSNqNb/rbZVNB9xIxRPp0MuqnxDmruQAHh3A3waupZIVGRTbGra0YbppnMu+dVpDQroRMITv2r7sORTF3HXpUFxHZOqBytwcuZMubJ5ND2nd+OlX7ipxzOWnS7lUOZDwklPeS8CA7iYZszpQeeReDwn6vuUYX+6nc0kvM0cDfSq4hYhuTTJLGkPbdOlmApZ2rmU/ktdR3g8nhRmAb6kXT3mEZ15H16B11yZMjPXZdZXRSx4f654ylGTpcYpXAKhTKJPEpDdhM="
    branches:
      - master
      - develop
  apt:
    packages:
      - oracle-java8-installer
script:
  - ./gradlew check
  - ./gradlew sonarqube
  - ./gradlew cucumber
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
