language: java
dist: trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: mrombout-github
jobs:
  include:
  - stage: compile
    script: "./gradlew assemble"
  - stage: test
    script: "./gradlew test"
  - stage: analysis
    script: "./gradlew sonarqube"
  - stage: package
    script: "./gradlew distZip"
  - stage: package
    script: "./gradlew distTar"
  - stage: deploy
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: FyydIutQ2Ps4Q9N+4iUqEkv+22abxfsMCDK+40qyy5vrnWCFvjGekjGuxGrRXd7Mgm2wjBqGsRAvfAA6fwiw9iVAERHlYdpU085aAWno/Ffwjxi+KnboOc91nyns6r2hRKH1LZFB9LeXahWW8fxWtoXjheN9FtZPRMfcm3TNhNL49cXl0VJHZ8Sf1Fse3ORDeXM4BIxJypZGlc6SXVfE9w7+nthaXKvbXeFQ3V5FVBr7ZqP1tNMaSkqzsYKuX9EWYeOHkOhmElXLI5I/nB+DJg6Aem+6mv+WmCYjxol3HjKgs8sSJMqpYtqP+NvK1P5KeptuIN2H4jXBPD+BA0cMCB5rGClm5o0KtsZJJKXgEmPElR/X62CyPMjUzivISJwz++5ZO1NnOuyucYccB7Cn2/7upfUugX1seohXMe0nZ+kMVq7ogkhjfqkLybTtqKQg5NBWXbkHsPzBQT0RDCR3Hr04KoDeeFHINhHjxdpbJdMkqiNT8V9pFCzBXgxhBU/pxaYnzJ0T8aK3Xf8Oy4VioSkBHtcKi+hhwJsDW2+20ncMSDVQkYWcz8tsHnNUPPEtHm2mvKuJHWXhvy4x7caQNKHS2DcOtL/rQys3HTLZ4ijg/m1seryd6wfSLN4VArh1lxv3hyv11OixATsBy0pGlECOovVu+Pu+xNaLV4aEEdU=
      file:
      - CommandLine/build/distributions/Spiner-CommandLine-0.1.2.zip
      - CommandLine/build/distributions/Spiner-CommandLine-0.1.2.tar
      - FrontEnd/build/distributions/Spiner-0.1.2.zip
      - FrontEnd/build/distributions/Spiner-0.1.2.tar
      on:
        tags: true
      skip_cleanup: true
      overwrite: true
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
